Belajar Numpy

Numpy adalah pustaka python open source yang digunakan hampir disemua bidang data science, Numpy itu kegunaanya untuk melakukan operasi matematika, dapat dikolaborasikan dengan library lain. Pada intinya Numpy dapat membuat multidimensi list atau matriks. 

1. Cara menginstal Numpy

In [19]:
import numpy
print(numpy.__version__)

1.26.4


Basic dari numpy adalah array. Array itu apa?

Array

Basic untuk pembuatan array dengan numpy

In [3]:
import numpy as np #kolom sudah aktiv dan berjalan

In [5]:
#untuk membuat kita menggunakan np.array()
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
#array isinya 0 sebanyak 5
b = np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#array isinya 1 sebanyak 5 kali
c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
#array kosong np.empty

In [16]:
#(start, stop, step)
#for i in range (1,11,2)
#arange (start, stop, step)
d = np.arange(4)
d

array([0, 1, 2, 3])

In [57]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [19]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Tambah array, hapus array, dan mengurutkan array

Menambahkan data kedalam Array

In [31]:
#np.append()
array1 = np.array([7,3,11,4,18])
array1 = np.append(array1,[99,100])
array1

array([  7,   3,  11,   4,  18,  99, 100])

Remove

In [33]:
array1

array([  7,   3,  11,   4,  18,  99, 100])

In [37]:
array1_hapus = np.delete(array1,2)
array1_hapus

array([  7,   3,   4,  18,  99, 100])

Sort

In [41]:
np.sort(array1)

array([  3,   4,   7,  11,  18,  99, 100])

Array 2Dimensi

In [44]:
#cirikhas dari dimensi
#satu dimensi
array_baru = np.array([2,3,4,5,6,7])
array_baru

array([2, 3, 4, 5, 6, 7])

In [8]:
#dua dimensi
array_2d = np.array([
                    [1,2,3,3],  #baris 0
                    [4,5,6,0],  #baris 1
                    [4,2,1,2],  #baris 2
                    [11,10,4,3] ##baris 3
                   ])
array_2d

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  0],
       [ 4,  2,  1,  2],
       [11, 10,  4,  3]])

In [9]:
#mau mengakses ROW/BARIS
array_2d[3]

array([11, 10,  4,  3])

In [13]:
#mau mengakses baris dan kolom
array_2d[1,2]

6

In [15]:
#mau mengakses kolom saja
array_2d[:,2] #kolom 3

array([3, 6, 1, 4])

In [16]:
#mau mengakses kolom saja
array_2d[:,0] #kolom 1

array([ 1,  4,  4, 11])

In [17]:
#mau mengakses 2 kolom
array_2d[:,[0,2]] #kolom 1 dan 3

array([[ 1,  3],
       [ 4,  6],
       [ 4,  1],
       [11,  4]])

In [18]:
array_2d[:,[0,1]]

array([[ 1,  2],
       [ 4,  5],
       [ 4,  2],
       [11, 10]])

ini untuk reshape

In [6]:
d = np.arange(6)
d #1 baris 6 kolom

array([0, 1, 2, 3, 4, 5])

In [7]:
d_reshape = d.reshape(3,2)
d_reshape

array([[0, 1],
       [2, 3],
       [4, 5]])

In [49]:
#tugas mini quiz
#1. buatlah array yang berisikan nilai 1-1000 dengan step bernilai 10
#2. buatlah array yang berisikan bilangan genap dari 0-10 lalu tambahkan nilai 100 didalam listnya 
#3. buatlah array bernilai 0 sebanyak 20 kali 

In [60]:
s = np.arange(1,1000,10)
s

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511,
       521, 531, 541, 551, 561, 571, 581, 591, 601, 611, 621, 631, 641,
       651, 661, 671, 681, 691, 701, 711, 721, 731, 741, 751, 761, 771,
       781, 791, 801, 811, 821, 831, 841, 851, 861, 871, 881, 891, 901,
       911, 921, 931, 941, 951, 961, 971, 981, 991])

In [53]:
x = np.array([2,4,6,8,10])
x = np.append(x,[100])
x

array([  2,   4,   6,   8,  10, 100])

In [56]:
z = np.zeros(20)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Indexing dan Slicing 

In [62]:
array3 = np.array([2,3,4,6,32,11,5,12,77,100])
array3

array([  2,   3,   4,   6,  32,  11,   5,  12,  77, 100])

In [64]:
print(array3[:-7])

[2 3 4]


In [65]:
kata = "Python"
print(kata[::-1]) #reverse

nohtyP


In [82]:
#miniQuiz 2 akses mini data
array_miniQuiz = np.array([
                     [6,12,32,42],  ##baris 0
                     [2,232,12,23],  ##baris 1
                     [41,22,13,24],  ##baris 2
                     [111,210,42,34] ##baris 3
                    ])
# 1. Tolong berikan output dengan mengakses kolom 2 dan 3
# 2. Tolong berikan output dengan mengakes baris 2 dengan elemen data ke 1
# 3. Tolong berikan output dengan mengakses bari 1 dan 2

In [86]:
array_miniQuiz[:,[2,3]]

array([[32, 42],
       [12, 23],
       [13, 24],
       [42, 34]])

In [87]:
array_miniQuiz[2,1]

22

In [89]:
array_miniQuiz[1:3]

array([[  2, 232,  12,  23],
       [ 41,  22,  13,  24]])

In [ ]:
#miniquiz slicing
#1. Aku punya kata "NGODING" ---> DING
#2. Aku punya kata "Kereta" ---> RETA
#3. Aku punya kata "JAUH" ---> huaj

In [91]:
word = "NGODING"
word.replace("NGO","")

'DING'

In [97]:
word1 = "Kereta"
word1.replace("Ke","").upper()

'RETA'

In [102]:
word2 = "JAUH"
word2[::-1].lower()

'huaj'

shape and size

In [20]:
array_example = np.array([[9,8,5,4],
                         [10,11,12,13],
                         [6,8,7,4],
                         [2,3,4,5]
                        ])
array_example

array([[ 9,  8,  5,  4],
       [10, 11, 12, 13],
       [ 6,  8,  7,  4],
       [ 2,  3,  4,  5]])

Mengecek dimensi

In [21]:
array_example.ndim

2

In [24]:
sample_array = np.array([1,2,3,4])
sample_array.ndim

1

Mengecek ukuran data

In [25]:
array_example.size

16

In [26]:
sample_array.size

4

Mengecek jumlah baris dan kolom

In [27]:
#shape --> digit 1 (baris) digit 2 (kolom)
array_example.shape

(4, 4)

Re-shape

In [29]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [38]:
b = a.reshape(3,2)
print(b.shape)
print(b)

(3, 2)
[[0 1]
 [2 3]
 [4 5]]


In [39]:
c = a.reshape(2,3)
print(c.shape)
print(c)

(2, 3)
[[0 1 2]
 [3 4 5]]


In [40]:
d = a.reshape(6,1)
print(d.shape)
print(d)

(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


CONVERT 1D to 2D, 2D to 1D

In [47]:
print(a.shape)
print(a) # a hanya memuat 6 data
#1,2,3,4,5,6
#variable yang isinya 6 data 

(6,)
[0 1 2 3 4 5]


In [46]:
a2 = a[np.newaxis]
print("Jumlah baris dan kolom : ",a2.shape)
print("Dimensi array saat ini : ",a2.ndim)
print(a2)

Jumlah baris dan kolom :  (1, 6)
Dimensi array saat ini :  2
[[0 1 2 3 4 5]]


Ubah 2D ke 1D

In [48]:
array_example2 = array_example.flatten()
array_example2

array([ 9,  8,  5,  4, 10, 11, 12, 13,  6,  8,  7,  4,  2,  3,  4,  5])

In [52]:
array_example.shape

(4, 4)

In [53]:
array_example2.shape

(16,)

Logical Numpy

In [54]:
array_example

array([[ 9,  8,  5,  4],
       [10, 11, 12, 13],
       [ 6,  8,  7,  4],
       [ 2,  3,  4,  5]])

In [55]:
array_example>7

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [False, False, False, False]])

In [64]:
#metode 1
print(array_example[array_example>7])
print(array_example[array_example>7].ndim)
print(array_example[array_example>7].shape)
print(array_example[array_example>7].size)

[ 9  8 10 11 12 13  8]
1
(7,)
7


In [65]:
#metode 2 
seven_up = (array_example>7)
print(array_example[seven_up])

[ 9  8 10 11 12 13  8]


In [67]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
bilangan_genap = (d%2==0)
print(d[bilangan_genap])

[0 2 4 6 8]


In [71]:
#metode 3
bilangan_genap2 = d[d%2==0]
bilangan_genap2

array([0, 2, 4, 6, 8])

In [72]:
#d > 2 dan d<11
#12 < age <15
#operator and(&)
dobel_logic = d[(d>2) & (d<11)]
dobel_logic

array([3, 4, 5, 6, 7, 8, 9])

In [73]:
dobel_logic2= d[(d>2) | (d<11)]
dobel_logic2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
age = 17
if (age < 12) and (age>15):
    print("Remaja")
else:
    print("Anak")

#and --> python, &--> numpy ===> ketika salah satu kondisi tidak terpenuhi maka dia akan FALSE
#or ---> ketika salah satu kondisi terpenuhi, TRUE--> eksekusi code

Anak


In [86]:
#b = 15
#if (a<14) and (a>10) # True or False
print((b<14) and (b>10))
#if (a>12) or (a<21) # True or False

False


Creating array from existing data

In [88]:
e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
tampil_e = e.view()
tampil_e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

.copy() --> Gunanya untuk 

In [91]:
tampil_ecopy = e.copy()
tampil_ecopy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

vstack, hstack, hsplit

In [94]:
a_1 = np.array([[1,1],[2,2],])
a_1

array([[1, 1],
       [2, 2]])

In [95]:
a_2 = np.array([[5,6],[7,8],])
a_2

array([[5, 6],
       [7, 8]])

In [96]:
#vstack --> menggabungkan 2 array menjadi 1 dengan susunan vertikal
result_vstack = np.vstack((a_1,a_2))
result_vstack

array([[1, 1],
       [2, 2],
       [5, 6],
       [7, 8]])

In [97]:
result_vstack.shape

(4, 2)

In [99]:
#hstack digunakan untuk menggabungkan 2 array menjadi 1 dengan susunan horizontal
result_hstack = np.hstack((a_1,a_2))
result_hstack

array([[1, 1, 5, 6],
       [2, 2, 7, 8]])

In [102]:
a_3 = np.array([[5,10],[7,5]])
a_4 = np.array([[6,3],[8,4]])

vstack_2 = np.vstack((a_3,a_4))
hstack_2 = np.hstack((a_3,a_4))
print(vstack_2)
print(hstack_2)

[[ 5 10]
 [ 7  5]
 [ 6  3]
 [ 8  4]]
[[ 5 10  6  3]
 [ 7  5  8  4]]


Operator matematika numpy

In [107]:
bilangan1 = np.array([8,2,3])
bilangan2 = np.array([1,2,3])

#pertambahan
result_kurang = bilangan1 - bilangan2
result_kurang

array([7, 0, 0])

In [108]:
#perkalian
result_kali = bilangan1 * bilangan2
result_kali

array([8, 4, 9])

In [109]:
#pembagian
result_bagi = bilangan1 // bilangan2
result_bagi

array([8, 1, 1])

In [111]:
#Quiz terakhir numpy
#soal reshape
#array disimpan di variabel z bialngan 1-100 dengan kelipatan 5
#ubah lah dari 1d ke 2d
#ubah jadi 2 baris

#soal vstack dan hstack
#array1 = [5,6,7,4,2,3,4,10]--> 1d---> resahpe
#array2 = [7,8,6,5,4,3,2,10]-->1d --> reshape

#vstack -->
#5 6
#7 4
#2 3
#4 10

#hstack-->
#5 6 7 4 7 8 6 5
#2 3 4 10 4 3 2 10

In [115]:
z = np.arange(5,101,5)
z

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [118]:
z.shape

(20,)

In [120]:
z_2d = z.reshape(2,10)
z_2d

array([[  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75,  80,  85,  90,  95, 100]])

In [129]:
x = z.reshape(10,2)
print(x.shape)
print(x)

(10, 2)
[[  5  10]
 [ 15  20]
 [ 25  30]
 [ 35  40]
 [ 45  50]
 [ 55  60]
 [ 65  70]
 [ 75  80]
 [ 85  90]
 [ 95 100]]


In [147]:
array1 = np.array([[5,6],[7,4],
                   [2,3],[4,10],])
array1

array([[ 5,  6],
       [ 7,  4],
       [ 2,  3],
       [ 4, 10]])

In [149]:
array2 = np.array([[7,8],[6,5],
                   [4,3],[2,10],])
array2

array([[ 7,  8],
       [ 6,  5],
       [ 4,  3],
       [ 2, 10]])

In [150]:
result_vstack = np.vstack(array1)
result_vstack

array([[ 5,  6],
       [ 7,  4],
       [ 2,  3],
       [ 4, 10]])

In [151]:
result_hstack = np.hstack((array1, array2))
print(result_hstack)

[[ 5  6  7  8]
 [ 7  4  6  5]
 [ 2  3  4  3]
 [ 4 10  2 10]]
